export const PORT = 9001;
export const WELCOME_MESSAGE = 'Welcome to TwitterAPI REST by GD_DEV ^_^!';

export const CONSUMER_KEY = 'YOUR CONSUMER KEY';
export const CONSUMER_SECRET = 'YOUR CONSUMER SECRET';
export const ACCESS_TOKEN_KEY = 'YOUR ACCESS TOKEN KEY';
export const ACCESS_TOKEN_SECRET = 'YOUR ACCESS TOKEN SECRET';
